/*
  # Create Farm2Hand_product table and populate with mockup data

  1. New Tables
    - `Farm2Hand_product`
      - `id` (bigint, primary key, auto-generated)
      - `product_name` (text, product name)
      - `product_price` (bigint, price in Thai Baht)
      - `product_unit` (text, unit of measurement)
      - `product_tag` (text, comma-separated tags)
      - `product_organic` (boolean, organic certification)
      - `product_rating` (bigint, rating out of 5, stored as integer * 10)
      - `product_owner` (bigint, foreign key to Farm2Hand_user.id)
      - `product_category` (text, product category)
      - `product_description` (text, product description)
      - `product_image` (text, image URL)
      - `product_stock` (bigint, available stock)
      - `product_reviews` (bigint, number of reviews)
      - `product_discount` (bigint, discount percentage)
      - `in_stock` (boolean, availability status)

  2. Security
    - Enable RLS on `Farm2Hand_product` table
    - Add policies for public read access and owner write access

  3. Sample Data
    - Insert 25+ mockup products across 5 categories
    - Fresh Vegetables (7 products)
    - Fruits (6 products)
    - Rice (5 products)
    - Eggs (4 products)
    - Out-of-Season Products (6 products)
*/

-- Create the product table
CREATE TABLE IF NOT EXISTS public."Farm2Hand_product" (
  id bigint generated by default as identity not null,
  product_name text null,
  product_price bigint null,
  product_unit text null,
  product_tag text null,
  product_organic boolean null,
  product_rating bigint null,
  product_owner bigint null,
  product_category text null,
  product_description text null,
  product_image text null,
  product_stock bigint null,
  product_reviews bigint null,
  product_discount bigint null,
  in_stock boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint Farm2Hand_product_pkey primary key (id),
  constraint Farm2Hand_product_product_owner_fkey foreign key (product_owner) references "Farm2Hand_user" (id) on update cascade on delete cascade
) tablespace pg_default;

-- Enable RLS
ALTER TABLE public."Farm2Hand_product" ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Anyone can view products"
  ON public."Farm2Hand_product"
  FOR SELECT
  USING (true);

-- Create policy for owners to manage their products
CREATE POLICY "Owners can manage their products"
  ON public."Farm2Hand_product"
  FOR ALL
  USING (product_owner = (current_setting('app.current_user_id', true))::bigint);

-- Create policy for authenticated users (fallback)
CREATE POLICY "Authenticated users can manage products"
  ON public."Farm2Hand_product"
  FOR ALL
  TO authenticated
  USING (true);

-- Insert mockup data for Fresh Vegetables (7 products)
INSERT INTO public."Farm2Hand_product" (
  product_name, product_price, product_unit, product_tag, product_organic, 
  product_rating, product_owner, product_category, product_description, 
  product_image, product_stock, product_reviews, product_discount, in_stock
) VALUES
-- Fresh Vegetables
(
  'ผักกาดหอมออร์แกนิค', 45, 'ถุง', 'ปลอดสารพิษ,สดใหม่,ออร์แกนิค', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Fresh Vegetables', 'ผักกาดหอมปลอดสารพิษ ปลูกด้วยวิธีธรรมชาติ',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  25, 203, null, true
),
(
  'คะน้าไฮโดรโปนิกส์', 35, 'ถุง', 'ไฮโดรโปนิกส์,สะอาด,กรอบ', true,
  47, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Fresh Vegetables', 'คะน้าปลูกด้วยระบบไฮโดรโปนิกส์ สะอาด ปลอดภัย',
  'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=400',
  30, 156, null, true
),
(
  'ผักบุ้งจีน', 25, 'ถุง', 'สดใหม่,กรอบ,หวาน', false,
  46, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Fresh Vegetables', 'ผักบุ้งจีนสดใหม่ เก็บในตอนเช้า กรอบหวาน',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  40, 89, null, true
),
(
  'ผักชีฝรั่ง', 30, 'ถุง', 'หอม,สดใหม่,ออร์แกนิค', true,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Fresh Vegetables', 'ผักชีฝรั่งหอมกรุ่น เหมาะสำหรับทำสลัด',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  20, 124, null, true
),
(
  'แครอทเบบี้', 95, 'กก.', 'หวาน,กรอบ,ออร์แกนิค', true,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Fresh Vegetables', 'แครอทเบบี้หวานกรอบ ขนาดเล็กน่ารัก เหมาะสำหรับเด็ก',
  'https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg?auto=compress&cs=tinysrgb&w=400',
  15, 167, null, true
),
(
  'มะเขือเทศราชินี', 80, 'กก.', 'หวาน,สดใหม่,คุณภาพดี', false,
  47, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Fresh Vegetables', 'มะเขือเทศราชินีสีแดงสด รสชาติหวานอมเปรี้ยว',
  'https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=400',
  35, 89, null, true
),
(
  'หอมแดงออร์แกนิค', 120, 'กก.', 'หอม,หวาน,ออร์แกนิค', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Fresh Vegetables', 'หอมแดงออร์แกนิค หอมหวาน เก็บได้นาน',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  25, 145, null, true
),

-- Fruits (6 products)
(
  'มะม่วงน้ำดอกไม้', 120, 'กก.', 'หวาน,สดใหม่,ออร์แกนิค', true,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Fruits', 'มะม่วงน้ำดอกไม้สดใหม่ หวานฉ่ำ เก็บจากต้นในวันเดียวกัน',
  'https://images.pexels.com/photos/2294471/pexels-photo-2294471.jpeg?auto=compress&cs=tinysrgb&w=400',
  20, 156, 10, true
),
(
  'กล้วยหอมทอง', 60, 'หวี', 'หวาน,สุกพอดี,หอม', false,
  46, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Fruits', 'กล้วยหอมทองหวานหอม เนื้อนุ่ม สุกพอดี',
  'https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=400',
  50, 124, 5, true
),
(
  'ส้มโอขาวน้ำหวาน', 150, 'ลูก', 'หวาน,ฉ่ำ,คุณภาพดี', false,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Fruits', 'ส้มโอขาวน้ำหวาน เนื้อฉ่ำ หวานเข้มข้น',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  0, 134, null, false
),
(
  'มะละกอสุก', 40, 'ลูก', 'หวาน,นุ่ม,สุกพอดี', false,
  45, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Fruits', 'มะละกอสุกหวาน เนื้อนุ่ม สีส้มสวย',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  30, 98, null, true
),
(
  'แก้วมังกรขาว', 80, 'กก.', 'หวาน,กรอบ,ออร์แกนิค', true,
  47, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Fruits', 'แก้วมังกรขาวหวานเซาะ เนื้อกรอบ มีประโยชน์',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  25, 112, null, true
),
(
  'สับปะรดภูเก็ต', 50, 'ลูก', 'หวาน,หอม,ฉ่ำ', false,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Fruits', 'สับปะรดภูเก็ตหวานหอม เนื้อเหลือง น้ำหวาน',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  40, 156, null, true
),

-- Rice (5 products)
(
  'ข้าวหอมมะลิ', 45, 'กก.', 'หอม,หวาน,เก็บใหม่', false,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Rice', 'ข้าวหอมมะลิแท้ 100% หอมหวาน เก็บใหม่',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  100, 245, null, true
),
(
  'ข้าวกล้องออร์แกนิค', 55, 'กก.', 'ออร์แกนิค,ใยอาหารสูง,มีประโยชน์', true,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Rice', 'ข้าวกล้องออร์แกนิค มีประโยชน์ ใยอาหารสูง',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  80, 189, null, true
),
(
  'ข้าวเหนียวขาว', 50, 'กก.', 'เหนียว,นุ่ม,หอม', false,
  47, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Rice', 'ข้าวเหนียวขาวเก่า เหนียวนุ่ม หอมหวาน',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  60, 134, null, true
),
(
  'ข้าวแดงออร์แกนิค', 65, 'กก.', 'ออร์แกนิค,แอนโทไซยานิน,สีธรรมชาติ', true,
  46, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Rice', 'ข้าวแดงออร์แกนิค สีแดงธรรมชาติ มีแอนโทไซยานิน',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  40, 98, null, true
),
(
  'ข้าวดำออร์แกนิค', 75, 'กก.', 'ออร์แกนิค,ต้านอนุมูลอิสระ,สีธรรมชาติ', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Rice', 'ข้าวดำออร์แกนิค สีดำธรรมชาติ มีสารต้านอนุมูลอิสระ',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  30, 167, null, true
),

-- Eggs (4 products)
(
  'ไข่ไก่สด', 120, 'แผง', 'สดใหม่,ไก่ปล่อย,ออร์แกนิค', true,
  47, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Eggs', 'ไข่ไก่สดใหม่ เก็บในวันเดียวกัน ไก่เลี้ยงแบบปล่อย',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  50, 98, null, true
),
(
  'ไข่ไก่ออร์แกนิค', 150, 'แผง', 'ออร์แกนิค,ธรรมชาติ,ปลอดยา', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Eggs', 'ไข่ไก่ออร์แกนิค ไก่กินอาหารธรรมชาติ ไม่ใช้ยาปฏิชีวนะ',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  30, 156, null, true
),
(
  'ไข่เป็ดสด', 80, 'แผง', 'สดใหม่,ขนาดใหญ่,ทำขนม', false,
  46, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Eggs', 'ไข่เป็ดสดใหม่ ขนาดใหญ่ เหมาะทำขนมไทย',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  25, 89, null, true
),
(
  'ไข่นกกระทา', 60, 'แผง', 'สดใหม่,เข้มข้น,ออร์แกนิค', true,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Eggs', 'ไข่นกกระทาสดใหม่ ขนาดเล็ก รสชาติเข้มข้น',
  'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=400',
  40, 124, null, true
),

-- Out-of-Season Products (6 products)
(
  'สตรอเบอร์รี่นอกฤดู', 200, 'กล่อง', 'นอกฤดู,โรงเรือน,หวาน', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Out-of-Season Products', 'สตรอเบอร์รี่นอกฤดูกาล ปลูกในโรงเรือน หวานฉ่ำ',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  15, 89, 15, true
),
(
  'ทุเรียนนอกฤดู', 300, 'กก.', 'นอกฤดู,หวาน,มัน', false,
  48, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Out-of-Season Products', 'ทุเรียนนอกฤดูกาล เนื้อเหลือง หวานมัน',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  10, 67, null, true
),
(
  'ลำไยนอกฤดู', 180, 'กก.', 'นอกฤดู,หวาน,กรอบ', false,
  47, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Out-of-Season Products', 'ลำไยนอกฤดูกาล เนื้อใส หวานกรอบ',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  20, 98, null, true
),
(
  'ลิ้นจี่นอกฤดู', 220, 'กก.', 'นอกฤดู,หวาน,ฉ่ำ', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'wichai@organic.com' LIMIT 1),
  'Out-of-Season Products', 'ลิ้นจี่นอกฤดูกาล เนื้อขาวใส หวานฉ่ำ',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  0, 134, null, false
),
(
  'เงาะนอกฤดู', 160, 'กก.', 'นอกฤดู,หวาน,เซาะ', false,
  46, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'farmer@test.com' LIMIT 1),
  'Out-of-Season Products', 'เงาะนอกฤดูกาล เนื้อขาว หวานเซาะ',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  12, 76, null, true
),
(
  'มังคุดนอกฤดู', 250, 'กก.', 'นอกฤดู,ราชินี,หวาน', true,
  49, (SELECT id FROM public."Farm2Hand_user" WHERE "Email" = 'somchai@farm.com' LIMIT 1),
  'Out-of-Season Products', 'มังคุดนอกฤดูกาล ราชินีแห่งผลไม้ หวานเซาะ',
  'https://images.pexels.com/photos/1414130/pexels-photo-1414130.jpeg?auto=compress&cs=tinysrgb&w=400',
  8, 145, null, true
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_product_category ON public."Farm2Hand_product"(product_category);
CREATE INDEX IF NOT EXISTS idx_product_owner ON public."Farm2Hand_product"(product_owner);
CREATE INDEX IF NOT EXISTS idx_product_organic ON public."Farm2Hand_product"(product_organic);
CREATE INDEX IF NOT EXISTS idx_product_in_stock ON public."Farm2Hand_product"(in_stock);
CREATE INDEX IF NOT EXISTS idx_product_created_at ON public."Farm2Hand_product"(created_at);